#!/bin/bash

# ======================================
#  Constants
# ======================================
uuid='timepp@matthiakl'

type='APPLET'

watch_dirs=(
    '.'
    'img'
    '@./.git'
)


# ======================================
#  Functions
# ======================================
reload_applet() {
    dbus-send --session                                           \
              --dest=org.Cinnamon.LookingGlass --type=method_call \
              /org/Cinnamon/LookingGlass                          \
              org.Cinnamon.LookingGlass.ReloadExtension           \
              string:"$uuid"                                      \
              string:"$type"
}

# useful for opening the menu automatically too
toggle_menu() {
    xdotool mousemove 1695 7
    xdotool click 1
}


# ======================================
#  Watch loop
# ======================================
while
    reload_applet
	sleep 1
    toggle_menu

    # test
    inotifywait --format '%e %w%f' -qre modify "${watch_dirs[@]}"
do :; done
